"""golike-gauth — generate g-auth / g-device-id / sig for Golike gateway."""

from .core import (
    APP_CLIENT,
    APP_VERSION,
    BASE_API,
    MOBILE_UA,
    SALT,
    SECTOKEN_SALT,
    SECURITY_API,
    GolikeAuth,
    body_hash,
    build_headers,
    decode_g_auth,
    derive_aes_key,
    fetch_security_session,
    fetch_user_me,
    generate_device_id,
    generate_g_auth,
    generate_sectoken_g_auth,
    generate_sig,
    mint_security_token,
    jwt_payload,
    jwt_user_id,
    make_t_header,
    normalize_path,
    parse_signing_key,
    resolve_signing_key,
)

__version__ = "0.1.8"
__all__ = [
    "APP_CLIENT",
    "APP_VERSION",
    "BASE_API",
    "MOBILE_UA",
    "SALT",
    "SECTOKEN_SALT",
    "SECURITY_API",
    "GolikeAuth",
    "body_hash",
    "build_headers",
    "decode_g_auth",
    "derive_aes_key",
    "fetch_security_session",
    "fetch_user_me",
    "generate_device_id",
    "generate_g_auth",
    "generate_sectoken_g_auth",
    "generate_sig",
    "mint_security_token",
    "jwt_payload",
    "jwt_user_id",
    "make_t_header",
    "normalize_path",
    "parse_signing_key",
    "resolve_signing_key",
    "__version__",
]
